version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: gymcrm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gymcrmdb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    
  backend:
    build: ./backend             
    container_name: gymcrm-backend
    volumes:
      - ./backend:/app           
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: gymcrmdb

volumes:
  db_data: